version: "3"

services:
  traefik:
    image: traefik:v2.10.3
    command:
      - --ping.entrypoint=web
      - --providers.file.directory=/config
      - --entrypoints.web.address=:8888
      - --entrypoints.websecure.address=:8889
      - --entrypoints.websecure.http.tls=true

      - --log.level=DEBUG
      #- --accesslog=true
    network_mode: host
    volumes:
      - ./config:/config
    environment:
      - HOSTNAME

  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
