version: "3"
services:
  traefik:
    image: traefik:v2.11.3
    restart: unless-stopped
    command:
      - --api
      - --api.dashboard=true
      - --ping=true
      - --ping.entrypoint=websecure
      - --providers.file.directory=/config
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Specify the network name of this docker-compose file, if traefik is used
      #- --providers.docker.network=rr_default

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt

      # Set your letsencrypt email in the .env file, also the domain for which your certificate should be created
      - --certificatesresolvers.letsencrypt.acme.email=${letsencrypt_email}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Comment out next line to get letsencrypt production certificates
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

      #- '--log.level=DEBUG'
      #- - --accesslog=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme-store:/acme
      - ./tls.yaml:/config/tls.yaml
    labels:
      - traefik.enable=true
      # since Traefik don't allow to change the api path the referer is used as rule (https://github.com/traefik/traefik/issues/5853)
      - traefik.http.routers.dashboard.rule=Host(`${domain}`) && (PathPrefix(`/traefik/dashboard`) || HeadersRegexp(`Referer`, `.*\/traefik\/dashboard\/.*`))
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.middlewares=strip-prefix-traefik
      - traefik.http.middlewares.strip-prefix-traefik.stripprefix.prefixes=/traefik

      - traefik.http.routers.dashboard-redirect.rule=PathPrefix(`/traefik`)
      - traefik.http.routers.dashboard-redirect.service=noop@internal
      - traefik.http.routers.dashboard-redirect.entrypoints=websecure
      - traefik.http.routers.dashboard-redirect.middlewares=dashboard-redirect
      - traefik.http.middlewares.dashboard-redirect.redirectregex.regex=^(https://.*)/traefik.*
      - traefik.http.middlewares.dashboard-redirect.redirectregex.replacement=$${1}/traefik/dashboard/

  frontend:
    image: ghcr.io/poeschl/roborush:frontend
    restart: unless-stopped
    #environment:
    #  PLAUSIBLE_DOMAIN: <your domain>
    #  PLAUSIBLE_API_HOST: https://plausible.io
    labels:
      - traefik.enable=true
      - traefik.http.routers.roborush-frontend.rule=Host(`${domain}`) && PathPrefix(`/`)
      - traefik.http.routers.roborush-frontend.entrypoints=websecure

  backend:
    image: ghcr.io/poeschl/roborush:backend
    restart: unless-stopped
    depends_on:
      - database
    environment:
      # Activate dummy bots with random movement
      # SPRING_PROFILES_ACTIVE: "prod, dummybots"
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: superSecret
      # Insert an instance specific string
      #AUTH_ISSUER:
      # Insert a random string with a recommended length of 64 chars. If changed, all users need to re-login.
      #AUTH_KEY:
      # Set a fixed root password. If not set a random will be generated on first start
      #INITIAL_ROOT_PASSWORD:
    labels:
      - traefik.enable=true
      - traefik.http.routers.roborush-backend.rule=Host(`${domain}`) && PathPrefix(`/api`)
      - traefik.http.routers.roborush-backend.entrypoints=websecure

  database:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecret

volumes:
  acme-store:
  db-data:
