spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    validate-migration-naming: true
  mvc:
    servlet:
      path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  error:
    include-message: always
  tomcat:
    max-http-form-post-size: 10MB

logging:
  level:
    xyz.poeschl.pathseeker: debug

---
# This is a second config section which gets activated when the "test" spring profile is active
spring:
  config.activate.on-profile: test

  datasource:
    url: jdbc:tc:postgresql:15-alpine:///postgres?user=postgres

logging:
  level:
    # For testcontainers issues uncomment this
    # org.testcontainers: debug
